name: Run packer build on a template file

on:
  push:
    branches:
        - 'main'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: riznob/packer-build-action@v1.5
        with:
          templateFile: 'packer-template.json'
          varFile: 'packer-vars.json'
          workingDir: '.'
